# -*- coding: utf-8 -*-
"""proyecto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O6tfDmxs075pySQA2wgtK9ltxBZG4C1I
"""

import pandas as pd

from google.colab import drive
drive.mount("/content/drive/")

datos = pd.read_excel("/content/drive/MyDrive/BASES/datos.xlsx")
datos = datos.drop(columns=['Mes', 'Año', 'IMAE_ULT_12M'])

import pandas as pd
import openpyxl

matriz_cor = datos.corr()
matriz_cor = pd.DataFrame(matriz_cor)

matriz_cor

matriz_cor.to_excel("matriz.xlsx", index=False)

import seaborn as sns
import matplotlib.pyplot as plt

# Graficar la matriz de correlación
sns.heatmap(matriz_cor, cmap='coolwarm', annot=True)
plt.show()